add_requires("spdlog", "doctest", "toml++", "asio", "protobuf-cpp", {system=false})

target("Common")
    set_kind("static")
    add_packages("spdlog", "doctest", "toml++", "asio", "protobuf-cpp")
    add_includedirs("src")
    add_rules("protobuf.cpp")
    add_headerfiles("src/Common/**.hpp", "src/Common/**.h")
    add_headerfiles("src/net/**.hpp")
    add_files("src/net/MessageProto/**.proto", "src/net/**.cpp")
    ExterRule()

target("tests")
    set_kind("binary")
    add_packages("spdlog", "doctest", "toml++", "asio")
    add_deps("Common")
    add_includedirs("src")
    -- add_headerfiles("src/tests/*.h")
    add_files("src/tests/test.cpp")
    ExterRule()

target("ServerDemo")
    set_kind("binary")
    add_packages("spdlog", "doctest", "toml++", "asio","protobuf-cpp")
    add_deps("Common")
    add_includedirs("src")
    add_files("src/tests/ServerDemo.cpp")
    add_rules("protobuf.cpp")
    add_files("src/net/MessageProto/**.proto")
    ExterRule()
target("ClientDemo")
    set_kind("binary")
    add_packages("spdlog", "doctest", "toml++", "asio", "protobuf-cpp")
    add_deps("Common")
    add_includedirs("src")
    add_rules("protobuf.cpp")
    add_files("src/tests/ClientDemo.cpp")
    add_files("src/net/MessageProto/**.proto")
    ExterRule()
