add_requires("spdlog", "doctest", "toml++", "asio", "protobuf-cpp")

target("Common")
    set_kind("static")
    add_packages("spdlog", "doctest", "toml++", "asio")
    -- add_cxflags("/P")
    add_includedirs("src")
    add_files("src/Common/*.ixx", "src/net/*.ixx", "src/**.cpp")
    ExterRule()

target("tests")
    set_kind("binary")
    add_packages("spdlog", "doctest", "toml++", "asio", "protobuf-cpp")
    add_deps("Common")
    add_includedirs("src")
    add_rules("protobuf.cpp")
    add_files("src/proto/**.proto")
    add_headerfiles("src/tests/*.h")
    add_files("src/tests/*.cpp|src/tests/test_session.cpp")
    ExterRule()

target("testServer")
    set_kind("binary")
    add_packages("spdlog", "doctest", "toml++", "asio", "protobuf-cpp")
    add_deps("Common")
    add_includedirs("src")
    add_rules("protobuf.cpp")
    add_files("src/proto/**.proto")
    add_files("src/tests/test_session.cpp")
    ExterRule()
